### ISSUE TITLE
PullSecrets are not applied to configchecker from Agent Spec

### ISSUE THREAD

**Issue by bartekle** [kaasops/vector-operator#126]
Specifying imagePullSecrets in config check pod is not possible, which make the whole thing not working when using private repositories.

**Comment by zvlb** [comment]
Hi @bartekle! Thanks for the issue. 

I'll take a look soon at how to set up passing imagePullSecrets to the configCheck pods.

**Comment by zvlb** [comment]
Fixed in [v0.0.31](https://github.com/kaasops/vector-operator/releases/tag/v0.0.31) release
