### ISSUE TITLE
Vector agent doesn't collect his own logs by oneself with source type: "kubernetes_logs"

### ISSUE THREAD

**Issue by anatolychernov** [kaasops/vector-operator#76]
Highly likely the reason is in parameter k8s.VectorExcludeLabel: "true" at this place
https://github.com/kaasops/vector-operator/blob/4dc6c98cfb9193f865b175a205c239081c0447bc/controllers/factory/vector/vectoragent/vectoragent_controller.go#L128

**Comment by dkhachyan** [comment]
fixed:
[https://github.com/kaasops/vector-operator/pull/79]
